# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: Docker@2
  inputs:
    containerRegistry: 'devops-project-con'
    repository: 'vandycking/my-flask-img'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'

- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'Vandyck Adomako Mensah DevOps(2c8dc312-dea6-4470-8ad5-05e4b589b47d)'
    azureResourceGroup: 'networking-resource-group'
    kubernetesCluster: 'vd-aks-cluster'
    command: 'apply'
    arguments: '-f aks-terraform/application-manifest.yaml'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'